/**
 * Dataset de comunas chilenas con región y población (Censo 2017 INE).
 * Clave: nombre en minúsculas sin tildes, igual al formato de COMUNAS_REFERENCIA.
 * Fuente: Instituto Nacional de Estadísticas de Chile — censo.cl
 */
export type ComunaInfo = {
  region: string
  habitantes: number
}

export const COMUNAS_DATA: Record<string, ComunaInfo> = {
  'algarrobo':              { region: 'Valparaíso', habitantes: 12995 },
  'alhue':                  { region: 'Metropolitana de Santiago', habitantes: 5035 },
  'alto biobio':            { region: 'Biobío', habitantes: 5765 },
  'alto del carmen':        { region: 'Atacama', habitantes: 5115 },
  'alto hospicio':          { region: 'Tarapacá', habitantes: 108669 },
  'ancud':                  { region: 'Los Lagos', habitantes: 38530 },
  'andacollo':              { region: 'Coquimbo', habitantes: 11048 },
  'angol':                  { region: 'La Araucanía', habitantes: 54670 },
  'antofagasta':            { region: 'Antofagasta', habitantes: 361873 },
  'antuco':                 { region: 'Biobío', habitantes: 7325 },
  'arauco':                 { region: 'Biobío', habitantes: 35900 },
  'arica':                  { region: 'Arica y Parinacota', habitantes: 226068 },
  'aysen':                  { region: 'Aysén del Gral. Carlos Ibáñez del Campo', habitantes: 18380 },
  'buin':                   { region: 'Metropolitana de Santiago', habitantes: 79230 },
  'bulnes':                 { region: 'Ñuble', habitantes: 21395 },
  'cabildo':                { region: 'Valparaíso', habitantes: 20085 },
  'cabo de hornos':         { region: 'Magallanes y de la Antártica Chilena', habitantes: 1947 },
  'cabrero':                { region: 'Biobío', habitantes: 27020 },
  'calama':                 { region: 'Antofagasta', habitantes: 165459 },
  'calbuco':                { region: 'Los Lagos', habitantes: 32340 },
  'caldera':                { region: 'Atacama', habitantes: 17987 },
  'calera de tango':        { region: 'Metropolitana de Santiago', habitantes: 27850 },
  'calle larga':            { region: 'Valparaíso', habitantes: 14025 },
  'camarones':              { region: 'Arica y Parinacota', habitantes: 1042 },
  'camina':                 { region: 'Tarapacá', habitantes: 1398 },
  'canela':                 { region: 'Coquimbo', habitantes: 9516 },
  'canete':                 { region: 'Biobío', habitantes: 33895 },
  'carahue':                { region: 'La Araucanía', habitantes: 26285 },
  'cartagena':              { region: 'Valparaíso', habitantes: 26440 },
  'casablanca':             { region: 'Valparaíso', habitantes: 21095 },
  'castro':                 { region: 'Los Lagos', habitantes: 44460 },
  'catemu':                 { region: 'Valparaíso', habitantes: 11285 },
  'cauquenes':              { region: 'Maule', habitantes: 39590 },
  'cerrillos':              { region: 'Metropolitana de Santiago', habitantes: 79310 },
  'cerro navia':            { region: 'Metropolitana de Santiago', habitantes: 128980 },
  'chaiten':                { region: 'Los Lagos', habitantes: 7450 },
  'chanaral':               { region: 'Atacama', habitantes: 13530 },
  'chanco':                 { region: 'Maule', habitantes: 10505 },
  'chepica':                { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 12585 },
  'chiguayante':            { region: 'Biobío', habitantes: 83920 },
  'chillan':                { region: 'Ñuble', habitantes: 180809 },
  'chillan viejo':          { region: 'Ñuble', habitantes: 40590 },
  'chimbarongo':            { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 24620 },
  'cholchol':               { region: 'La Araucanía', habitantes: 12255 },
  'chonchi':                { region: 'Los Lagos', habitantes: 11875 },
  'cisnes':                 { region: 'Aysén del Gral. Carlos Ibáñez del Campo', habitantes: 6960 },
  'cobquecura':             { region: 'Ñuble', habitantes: 5685 },
  'cochamo':                { region: 'Los Lagos', habitantes: 4585 },
  'cochrane':               { region: 'Aysén del Gral. Carlos Ibáñez del Campo', habitantes: 3540 },
  'codegua':                { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 13255 },
  'coelemu':                { region: 'Ñuble', habitantes: 14455 },
  'coihueco':               { region: 'Ñuble', habitantes: 22545 },
  'coinco':                 { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 8620 },
  'colbun':                 { region: 'Maule', habitantes: 24745 },
  'colchane':               { region: 'Tarapacá', habitantes: 1501 },
  'colina':                 { region: 'Metropolitana de Santiago', habitantes: 120275 },
  'collipulli':             { region: 'La Araucanía', habitantes: 27840 },
  'coltauco':               { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 13485 },
  'combarbala':             { region: 'Coquimbo', habitantes: 14030 },
  'concepcion':             { region: 'Biobío', habitantes: 216061 },
  'conchali':               { region: 'Metropolitana de Santiago', habitantes: 133135 },
  'concon':                 { region: 'Valparaíso', habitantes: 47991 },
  'constitucion':           { region: 'Maule', habitantes: 46950 },
  'contulmo':               { region: 'Biobío', habitantes: 8515 },
  'copiapo':                { region: 'Atacama', habitantes: 158048 },
  'coquimbo':               { region: 'Coquimbo', habitantes: 227010 },
  'coronel':                { region: 'Biobío', habitantes: 108365 },
  'corral':                 { region: 'Los Ríos', habitantes: 5445 },
  'coyhaique':              { region: 'Aysén del Gral. Carlos Ibáñez del Campo', habitantes: 57447 },
  'cunco':                  { region: 'La Araucanía', habitantes: 16285 },
  'curacautin':             { region: 'La Araucanía', habitantes: 19400 },
  'curacavi':               { region: 'Metropolitana de Santiago', habitantes: 20835 },
  'curaco de velez':        { region: 'Los Lagos', habitantes: 3960 },
  'curanilahue':            { region: 'Biobío', habitantes: 32895 },
  'curarrehue':             { region: 'La Araucanía', habitantes: 8220 },
  'curepto':                { region: 'Maule', habitantes: 11425 },
  'curico':                 { region: 'Maule', habitantes: 148310 },
  'dalcahue':               { region: 'Los Lagos', habitantes: 15480 },
  'diego de almagro':       { region: 'Atacama', habitantes: 23450 },
  'donihue':                { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 12685 },
  'el bosque':              { region: 'Metropolitana de Santiago', habitantes: 163511 },
  'el carmen':              { region: 'Ñuble', habitantes: 14475 },
  'el monte':               { region: 'Metropolitana de Santiago', habitantes: 37545 },
  'el quisco':              { region: 'Valparaíso', habitantes: 15250 },
  'el tabo':                { region: 'Valparaíso', habitantes: 10685 },
  'empedrado':              { region: 'Maule', habitantes: 7615 },
  'ercilla':                { region: 'La Araucanía', habitantes: 11440 },
  'estacion central':       { region: 'Metropolitana de Santiago', habitantes: 129375 },
  'florida':                { region: 'Biobío', habitantes: 15585 },
  'freire':                 { region: 'La Araucanía', habitantes: 28070 },
  'freirina':               { region: 'Atacama', habitantes: 7820 },
  'fresia':                 { region: 'Los Lagos', habitantes: 13450 },
  'frutillar':              { region: 'Los Lagos', habitantes: 21285 },
  'futaleufu':              { region: 'Los Lagos', habitantes: 2420 },
  'futrono':                { region: 'Los Ríos', habitantes: 17520 },
  'galvarino':              { region: 'La Araucanía', habitantes: 15335 },
  'general lagos':          { region: 'Arica y Parinacota', habitantes: 1097 },
  'gorbea':                 { region: 'La Araucanía', habitantes: 19155 },
  'graneros':               { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 32795 },
  'guaitecas':              { region: 'Aysén del Gral. Carlos Ibáñez del Campo', habitantes: 1035 },
  'hijuelas':               { region: 'Valparaíso', habitantes: 17325 },
  'hualaihue':              { region: 'Los Lagos', habitantes: 13850 },
  'hualane':                { region: 'Maule', habitantes: 10745 },
  'hualpen':                { region: 'Biobío', habitantes: 93500 },
  'hualqui':                { region: 'Biobío', habitantes: 23895 },
  'huara':                  { region: 'Tarapacá', habitantes: 2791 },
  'huasco':                 { region: 'Atacama', habitantes: 8155 },
  'huechuraba':             { region: 'Metropolitana de Santiago', habitantes: 87615 },
  'illapel':                { region: 'Coquimbo', habitantes: 33890 },
  'independencia':          { region: 'Metropolitana de Santiago', habitantes: 100281 },
  'iquique':                { region: 'Tarapacá', habitantes: 191468 },
  'isla de maipo':          { region: 'Metropolitana de Santiago', habitantes: 32195 },
  'isla de pascua':         { region: 'Valparaíso', habitantes: 7750 },
  'juan fernandez':         { region: 'Valparaíso', habitantes: 959 },
  'la cisterna':            { region: 'Metropolitana de Santiago', habitantes: 88720 },
  'la cruz':                { region: 'Valparaíso', habitantes: 24875 },
  'la estrella':            { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 3985 },
  'la florida':             { region: 'Metropolitana de Santiago', habitantes: 366916 },
  'la granja':              { region: 'Metropolitana de Santiago', habitantes: 126820 },
  'la higuera':             { region: 'Coquimbo', habitantes: 4023 },
  'la ligua':               { region: 'Valparaíso', habitantes: 28455 },
  'la pintana':             { region: 'Metropolitana de Santiago', habitantes: 183660 },
  'la reina':               { region: 'Metropolitana de Santiago', habitantes: 95525 },
  'la serena':              { region: 'Coquimbo', habitantes: 221625 },
  'la union':               { region: 'Los Ríos', habitantes: 44090 },
  'lago ranco':             { region: 'Los Ríos', habitantes: 13080 },
  'lago verde':             { region: 'Aysén del Gral. Carlos Ibáñez del Campo', habitantes: 1170 },
  'laguna blanca':          { region: 'Magallanes y de la Antártica Chilena', habitantes: 576 },
  'laja':                   { region: 'Biobío', habitantes: 23420 },
  'lampa':                  { region: 'Metropolitana de Santiago', habitantes: 85285 },
  'lanco':                  { region: 'Los Ríos', habitantes: 17415 },
  'las cabras':             { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 22460 },
  'las condes':             { region: 'Metropolitana de Santiago', habitantes: 278415 },
  'lautaro':                { region: 'La Araucanía', habitantes: 30810 },
  'lebu':                   { region: 'Biobío', habitantes: 24910 },
  'licanten':               { region: 'Maule', habitantes: 8225 },
  'limache':                { region: 'Valparaíso', habitantes: 45765 },
  'linares':                { region: 'Maule', habitantes: 98580 },
  'litueche':               { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 7195 },
  'llaillay':               { region: 'Valparaíso', habitantes: 29350 },
  'llanquihue':             { region: 'Los Lagos', habitantes: 25920 },
  'llay llay':              { region: 'Valparaíso', habitantes: 29350 },
  'lo barnechea':           { region: 'Metropolitana de Santiago', habitantes: 105833 },
  'lo espejo':              { region: 'Metropolitana de Santiago', habitantes: 101105 },
  'lo prado':               { region: 'Metropolitana de Santiago', habitantes: 95768 },
  'lolol':                  { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 6110 },
  'loncoche':               { region: 'La Araucanía', habitantes: 21800 },
  'longavi':                { region: 'Maule', habitantes: 33170 },
  'lonquimay':              { region: 'La Araucanía', habitantes: 14670 },
  'los alamos':             { region: 'Biobío', habitantes: 22995 },
  'los andes':              { region: 'Valparaíso', habitantes: 72745 },
  'los angeles':            { region: 'Biobío', habitantes: 202153 },
  'los lagos':              { region: 'Los Ríos', habitantes: 25125 },
  'los muermos':            { region: 'Los Lagos', habitantes: 15650 },
  'los sauces':             { region: 'La Araucanía', habitantes: 12650 },
  'los vilos':              { region: 'Coquimbo', habitantes: 21249 },
  'lota':                   { region: 'Biobío', habitantes: 44970 },
  'lumaco':                 { region: 'La Araucanía', habitantes: 11555 },
  'machali':                { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 47430 },
  'macul':                  { region: 'Metropolitana de Santiago', habitantes: 112105 },
  'mafil':                  { region: 'Los Ríos', habitantes: 7995 },
  'maipu':                  { region: 'Metropolitana de Santiago', habitantes: 521627 },
  'malloa':                 { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 12805 },
  'marchihue':              { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 8545 },
  'maria elena':            { region: 'Antofagasta', habitantes: 6034 },
  'maria pinto':            { region: 'Metropolitana de Santiago', habitantes: 11540 },
  'mariquina':              { region: 'Los Ríos', habitantes: 27240 },
  'maule':                  { region: 'Maule', habitantes: 24785 },
  'maullin':                { region: 'Los Lagos', habitantes: 19880 },
  'mejillones':             { region: 'Antofagasta', habitantes: 13490 },
  'melipeuco':              { region: 'La Araucanía', habitantes: 7125 },
  'melipilla':              { region: 'Metropolitana de Santiago', habitantes: 119523 },
  'molina':                 { region: 'Maule', habitantes: 53010 },
  'monte patria':           { region: 'Coquimbo', habitantes: 33890 },
  'mostazal':               { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 29480 },
  'mulchen':                { region: 'Biobío', habitantes: 33015 },
  'nacimiento':             { region: 'Biobío', habitantes: 28460 },
  'nancagua':               { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 14250 },
  'natales':                { region: 'Magallanes y de la Antártica Chilena', habitantes: 20085 },
  'negrete':                { region: 'Biobío', habitantes: 8500 },
  'ninhue':                 { region: 'Ñuble', habitantes: 6285 },
  'niquen':                 { region: 'Ñuble', habitantes: 9875 },
  'nogales':                { region: 'Valparaíso', habitantes: 26845 },
  'nueva imperial':         { region: 'La Araucanía', habitantes: 38530 },
  'nunoa':                  { region: 'Metropolitana de Santiago', habitantes: 207274 },
  'o higgins':              { region: 'Aysén del Gral. Carlos Ibáñez del Campo', habitantes: 640 },
  'olivar':                 { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 26490 },
  'ollague':                { region: 'Antofagasta', habitantes: 318 },
  'olmue':                  { region: 'Valparaíso', habitantes: 16020 },
  'osorno':                 { region: 'Los Lagos', habitantes: 158248 },
  'ovalle':                 { region: 'Coquimbo', habitantes: 108936 },
  'padre hurtado':          { region: 'Metropolitana de Santiago', habitantes: 68375 },
  'padre las casas':        { region: 'La Araucanía', habitantes: 72930 },
  'paihuano':               { region: 'Coquimbo', habitantes: 4552 },
  'paillaco':               { region: 'Los Ríos', habitantes: 24285 },
  'paine':                  { region: 'Metropolitana de Santiago', habitantes: 90110 },
  'palena':                 { region: 'Los Lagos', habitantes: 2470 },
  'palmilla':               { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 8230 },
  'panguipulli':            { region: 'Los Ríos', habitantes: 38595 },
  'panquehue':              { region: 'Valparaíso', habitantes: 10485 },
  'papudo':                 { region: 'Valparaíso', habitantes: 6850 },
  'paredones':              { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 7995 },
  'parral':                 { region: 'Maule', habitantes: 43590 },
  'pedro aguirre cerda':    { region: 'Metropolitana de Santiago', habitantes: 113760 },
  'pelarco':                { region: 'Maule', habitantes: 8770 },
  'pelluhue':               { region: 'Maule', habitantes: 9285 },
  'pemuco':                 { region: 'Ñuble', habitantes: 9870 },
  'penaflor':               { region: 'Metropolitana de Santiago', habitantes: 78420 },
  'penalolen':              { region: 'Metropolitana de Santiago', habitantes: 236860 },
  'pencahue':               { region: 'Maule', habitantes: 8325 },
  'penco':                  { region: 'Biobío', habitantes: 46880 },
  'peralillo':              { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 7815 },
  'perquenco':              { region: 'La Araucanía', habitantes: 9680 },
  'petorca':                { region: 'Valparaíso', habitantes: 11985 },
  'peumo':                  { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 17350 },
  'pica':                   { region: 'Tarapacá', habitantes: 7163 },
  'pichidegua':             { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 17125 },
  'pichilemu':              { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 15630 },
  'pinto':                  { region: 'Ñuble', habitantes: 16395 },
  'pirque':                 { region: 'Metropolitana de Santiago', habitantes: 19125 },
  'pitrufquen':             { region: 'La Araucanía', habitantes: 24070 },
  'placilla':               { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 8015 },
  'portezuelo':             { region: 'Ñuble', habitantes: 6095 },
  'porvenir':               { region: 'Magallanes y de la Antártica Chilena', habitantes: 7990 },
  'pozo almonte':           { region: 'Tarapacá', habitantes: 24354 },
  'primavera':              { region: 'Magallanes y de la Antártica Chilena', habitantes: 405 },
  'providencia':            { region: 'Metropolitana de Santiago', habitantes: 142079 },
  'puchuncavi':             { region: 'Valparaíso', habitantes: 19122 },
  'pucon':                  { region: 'La Araucanía', habitantes: 31895 },
  'pudahuel':               { region: 'Metropolitana de Santiago', habitantes: 195735 },
  'puente alto':            { region: 'Metropolitana de Santiago', habitantes: 568106 },
  'puerto montt':           { region: 'Los Lagos', habitantes: 245902 },
  'puerto octay':           { region: 'Los Lagos', habitantes: 13650 },
  'puerto varas':           { region: 'Los Lagos', habitantes: 41840 },
  'pumanque':               { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 4290 },
  'punitaqui':              { region: 'Coquimbo', habitantes: 11420 },
  'punta arenas':           { region: 'Magallanes y de la Antártica Chilena', habitantes: 131315 },
  'puqueldon':              { region: 'Los Lagos', habitantes: 3455 },
  'puren':                  { region: 'La Araucanía', habitantes: 12240 },
  'purranque':              { region: 'Los Lagos', habitantes: 29885 },
  'putaendo':               { region: 'Valparaíso', habitantes: 17380 },
  'putre':                  { region: 'Arica y Parinacota', habitantes: 1915 },
  'puyehue':                { region: 'Los Lagos', habitantes: 13915 },
  'queilen':                { region: 'Los Lagos', habitantes: 4710 },
  'quellon':                { region: 'Los Lagos', habitantes: 28095 },
  'quemchi':                { region: 'Los Lagos', habitantes: 9890 },
  'quilaco':                { region: 'Biobío', habitantes: 5595 },
  'quilicura':              { region: 'Metropolitana de Santiago', habitantes: 184747 },
  'quilleco':               { region: 'Biobío', habitantes: 12505 },
  'quillon':                { region: 'Ñuble', habitantes: 10590 },
  'quillota':               { region: 'Valparaíso', habitantes: 83360 },
  'quilpue':                { region: 'Valparaíso', habitantes: 162790 },
  'quinchao':               { region: 'Los Lagos', habitantes: 12235 },
  'quinta de tilcoco':      { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 8395 },
  'quinta normal':          { region: 'Metropolitana de Santiago', habitantes: 101480 },
  'quintero':               { region: 'Valparaíso', habitantes: 28476 },
  'quirihue':               { region: 'Ñuble', habitantes: 12395 },
  'rancagua':               { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 232446 },
  'ranquil':                { region: 'Ñuble', habitantes: 8535 },
  'rauco':                  { region: 'Maule', habitantes: 10415 },
  'recoleta':               { region: 'Metropolitana de Santiago', habitantes: 148715 },
  'renaico':                { region: 'La Araucanía', habitantes: 12110 },
  'renca':                  { region: 'Metropolitana de Santiago', habitantes: 146102 },
  'rengo':                  { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 53815 },
  'requinoa':               { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 22915 },
  'retiro':                 { region: 'Maule', habitantes: 22105 },
  'rinconada':              { region: 'Valparaíso', habitantes: 10045 },
  'rio bueno':              { region: 'Los Ríos', habitantes: 35440 },
  'rio claro':              { region: 'Maule', habitantes: 17635 },
  'rio hurtado':            { region: 'Coquimbo', habitantes: 5280 },
  'rio ibanez':             { region: 'Aysén del Gral. Carlos Ibáñez del Campo', habitantes: 2300 },
  'rio negro':              { region: 'Los Lagos', habitantes: 21340 },
  'rio verde':              { region: 'Magallanes y de la Antártica Chilena', habitantes: 456 },
  'romeral':                { region: 'Maule', habitantes: 16430 },
  'saavedra':               { region: 'La Araucanía', habitantes: 16600 },
  'sagrada familia':        { region: 'Maule', habitantes: 14985 },
  'salamanca':              { region: 'Coquimbo', habitantes: 26007 },
  'san antonio':            { region: 'Valparaíso', habitantes: 87965 },
  'san bernardo':           { region: 'Metropolitana de Santiago', habitantes: 302283 },
  'san carlos':             { region: 'Ñuble', habitantes: 47490 },
  'san clemente':           { region: 'Maule', habitantes: 39310 },
  'san esteban':            { region: 'Valparaíso', habitantes: 15840 },
  'san fabian':             { region: 'Ñuble', habitantes: 5145 },
  'san fernando':           { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 72735 },
  'san francisco de mostazal': { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 29480 },
  'san gregorio':           { region: 'Magallanes y de la Antártica Chilena', habitantes: 832 },
  'san ignacio':            { region: 'Ñuble', habitantes: 20785 },
  'san javier':             { region: 'Maule', habitantes: 36710 },
  'san joaquin':            { region: 'Metropolitana de Santiago', habitantes: 94100 },
  'san jose de maipo':      { region: 'Metropolitana de Santiago', habitantes: 16830 },
  'san juan de la costa':   { region: 'Los Lagos', habitantes: 12960 },
  'san miguel':             { region: 'Metropolitana de Santiago', habitantes: 107794 },
  'san nicolas':            { region: 'Ñuble', habitantes: 14315 },
  'san pablo':              { region: 'Los Lagos', habitantes: 13585 },
  'san pedro':              { region: 'Metropolitana de Santiago', habitantes: 17790 },
  'san pedro de atacama':   { region: 'Antofagasta', habitantes: 10085 },
  'san pedro de la paz':    { region: 'Biobío', habitantes: 125235 },
  'san rafael':             { region: 'Maule', habitantes: 13480 },
  'san ramon':              { region: 'Metropolitana de Santiago', habitantes: 86830 },
  'san rosendo':            { region: 'Biobío', habitantes: 5070 },
  'san vicente':            { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 39120 },
  'santa barbara':          { region: 'Biobío', habitantes: 17695 },
  'santa cruz':             { region: "Libertador Gral. Bernardo O'Higgins", habitantes: 35495 },
  'santa juana':            { region: 'Biobío', habitantes: 12890 },
  'santa maria':            { region: 'Valparaíso', habitantes: 14820 },
  'santiago':               { region: 'Metropolitana de Santiago', habitantes: 404495 },
  'santo domingo':          { region: 'Valparaíso', habitantes: 9680 },
  'sierra gorda':           { region: 'Antofagasta', habitantes: 3185 },
  'talagante':              { region: 'Metropolitana de Santiago', habitantes: 68955 },
  'talca':                  { region: 'Maule', habitantes: 220357 },
  'talcahuano':             { region: 'Biobío', habitantes: 154380 },
  'taltal':                 { region: 'Antofagasta', habitantes: 11572 },
  'temuco':                 { region: 'La Araucanía', habitantes: 282415 },
  'teno':                   { region: 'Maule', habitantes: 23295 },
  'teodoro schmidt':        { region: 'La Araucanía', habitantes: 13730 },
  'tierra amarilla':        { region: 'Atacama', habitantes: 14321 },
  'tiltil':                 { region: 'Metropolitana de Santiago', habitantes: 18315 },
  'timaukel':               { region: 'Magallanes y de la Antártica Chilena', habitantes: 438 },
  'tirua':                  { region: 'Biobío', habitantes: 10765 },
  'tocopilla':              { region: 'Antofagasta', habitantes: 25187 },
  'tolten':                 { region: 'La Araucanía', habitantes: 13160 },
  'tome':                   { region: 'Biobío', habitantes: 51985 },
  'torres del paine':       { region: 'Magallanes y de la Antártica Chilena', habitantes: 1290 },
  'tortel':                 { region: 'Aysén del Gral. Carlos Ibáñez del Campo', habitantes: 507 },
  'traiguen':               { region: 'La Araucanía', habitantes: 23840 },
  'trehuaco':               { region: 'Ñuble', habitantes: 5865 },
  'tucapel':                { region: 'Biobío', habitantes: 17375 },
  'valdivia':               { region: 'Los Ríos', habitantes: 166080 },
  'vallenar':               { region: 'Atacama', habitantes: 50283 },
  'valparaiso':             { region: 'Valparaíso', habitantes: 296655 },
  'vichuquen':              { region: 'Maule', habitantes: 5575 },
  'victoria':               { region: 'La Araucanía', habitantes: 37440 },
  'vicuna':                 { region: 'Coquimbo', habitantes: 26648 },
  'vilcun':                 { region: 'La Araucanía', habitantes: 23465 },
  'villa alegre':           { region: 'Maule', habitantes: 16520 },
  'villa alemana':          { region: 'Valparaíso', habitantes: 124920 },
  'villarrica':             { region: 'La Araucanía', habitantes: 55050 },
  'vina del mar':           { region: 'Valparaíso', habitantes: 336289 },
  'vitacura':               { region: 'Metropolitana de Santiago', habitantes: 85483 },
  'yerbas buenas':          { region: 'Maule', habitantes: 17135 },
  'yumbel':                 { region: 'Biobío', habitantes: 22005 },
  'yungay':                 { region: 'Ñuble', habitantes: 21085 },
  'zapallar':               { region: 'Valparaíso', habitantes: 8350 },
}

/** Busca región y habitantes de una comuna normalizada. */
export function enriquecerComuna(normalizedName: string): ComunaInfo | null {
  const key = normalizedName.toLowerCase()
  return COMUNAS_DATA[key] ?? null
}
